// Copyright (c) 2026 Atakan DULKER. Licensed under the MIT License.

import Foundation

private struct SwiftPMResolvedPinFile: Decodable {
    let pins: [SwiftPMResolvedPin]
}

private struct SwiftPMResolvedPin: Decodable {
    let identity: String
    let location: String
    let state: SwiftPMResolvedPinState
}

private struct SwiftPMResolvedPinState: Decodable {
    let version: String?
    let revision: String?
}

/// Validates SwiftPM's CycloneDX package inventory against the root lockfile.
struct AxolotySwiftPMSBOMValidator {
    /// Validates each external dependency package in the SBOM against its lock pin.
    ///
    /// - Parameters:
    ///   - sbom: CycloneDX JSON generated by SwiftPM.
    ///   - resolved: The root `Package.resolved` bytes.
    /// - Throws: ``AxolotySwiftPMSBOMError`` when either document is malformed or the package inventories differ.
    func validate(sbom: Data, resolved: Data) throws(AxolotySwiftPMSBOMError) {
        let lock: SwiftPMResolvedPinFile
        do {
            lock = try JSONDecoder().decode(SwiftPMResolvedPinFile.self, from: resolved)
        } catch {
            throw .malformedPackageResolved
        }
        let document: [String: Any]
        do {
            guard let decoded = try JSONSerialization.jsonObject(with: sbom) as? [String: Any] else {
                throw AxolotySwiftPMSBOMError.malformedSBOM
            }
            document = decoded
        } catch let error as AxolotySwiftPMSBOMError {
            throw error
        } catch {
            throw .malformedSBOM
        }
        guard document["bomFormat"] as? String == "CycloneDX",
              let components = document["components"] as? [[String: Any]] else {
            throw AxolotySwiftPMSBOMError.malformedSBOM
        }

        let sbomPackages = components.compactMap { component -> (String, String, String?)? in
            guard let properties = component["properties"] as? [[String: String]],
                  properties.contains(where: { $0["name"] == "swift-entity" && $0["value"] == "swift-package" }),
                  let purl = component["purl"] as? String,
                  purl.contains("github.com/") else {
                return nil
            }
            let pedigree = component["pedigree"] as? [String: Any]
            let commits = pedigree?["commits"] as? [[String: Any]]
            let revision = commits?.compactMap { $0["uid"] as? String }.first
            return (component["name"] as? String ?? "", purl, revision)
        }
        guard !sbomPackages.isEmpty else { throw AxolotySwiftPMSBOMError.malformedSBOM }
        let mismatched = sbomPackages.compactMap { identity, purl, revision -> String? in
            guard let pin = lock.pins.first(where: { $0.identity.caseInsensitiveCompare(identity) == .orderedSame }),
                  purlMatches(purl, revision: revision, pin: pin) else {
                return identity
            }
            return nil
        }
        guard mismatched.isEmpty else {
            throw AxolotySwiftPMSBOMError.packageMismatch(mismatched.sorted())
        }
    }

    private func purlMatches(_ purl: String, revision: String?, pin: SwiftPMResolvedPin) -> Bool {
        guard purl.hasPrefix("pkg:swift/"),
              let at = purl.lastIndex(of: "@") else { return false }
        let identityInPath = purl[purl.index(purl.startIndex, offsetBy: "pkg:swift/".count)..<at]
            .split(separator: "/")
            .last
            .map(String.init)
        guard identityInPath?.lowercased() == pin.identity.lowercased() else { return false }
        let packageLocation = String(purl[purl.index(purl.startIndex, offsetBy: "pkg:swift/".count)..<at])
        guard sameRepository(packageLocation, pin.location) else { return false }

        let version = String(purl[purl.index(after: at)...]).split(separator: "?", maxSplits: 1).first.map(String.init)
        if let lockedVersion = pin.state.version {
            return version == lockedVersion && (pin.state.revision == nil || revision == pin.state.revision)
        }
        if let revision = pin.state.revision { return version == revision }
        return false
    }

    private func sameRepository(_ packageURL: String, _ lockedLocation: String) -> Bool {
        guard let package = URLComponents(string: "https://\(packageURL)"),
              let locked = URLComponents(string: lockedLocation),
              package.host?.lowercased() == locked.host?.lowercased() else {
            return false
        }
        return normalizedRepositoryPath(package.path) == normalizedRepositoryPath(locked.path)
    }

    private func normalizedRepositoryPath(_ path: String) -> String {
        let normalized = path.trimmingCharacters(in: CharacterSet(charactersIn: "/")).lowercased()
        return normalized.hasSuffix(".git") ? String(normalized.dropLast(4)) : normalized
    }
}

/// A SwiftPM SBOM could not be generated or matched to its lockfile.
enum AxolotySwiftPMSBOMError: Error, Equatable, Sendable, LocalizedError {
    case malformedSBOM
    case malformedPackageResolved
    case packageMismatch([String])

    var errorDescription: String? {
        switch self {
        case .malformedSBOM:
            return "SwiftPM SBOM is not a CycloneDX document with components"
        case .malformedPackageResolved:
            return "Package.resolved is malformed"
        case .packageMismatch(let packages):
            return "SwiftPM SBOM packages do not match Package.resolved: \(packages.joined(separator: ", "))"
        }
    }
}
