// Copyright (c) 2026 Atakan DULKER. Licensed under the MIT License.

import AxolotyProtocol
import AxolotyWire

/// Generates a concrete, statically noncapturing IO actor handler entry.
///
/// Apply the macro to a nongeneric enum that declares one compatible static
/// `receive(context:value:delivery:)` method. The generated C-convention
/// function pointer cannot capture application state; callers pass a numeric
/// context handle during registration instead.
///
/// - Parameter valueType: Portable endpoint value decoded before delivery.
@attached(member, names: named(Value), named(staticIoHandlerEntry))
@attached(extension, conformances: StaticIoActorHandler)
public macro StaticIoActor(_ valueType: Any.Type) =
    #externalMacro(
        module: "AxolotyStaticRuntimeMacrosImplementation",
        type: "StaticIoActorMacro"
    )

/// A macro-generated static IO actor handler.
public protocol StaticIoActorHandler {
    /// Application value decoded by the generated trampoline.
    associatedtype Value: IoEndpointValue

    /// Completed concrete handler entry generated by ``StaticIoActor(_:)``.
    static var staticIoHandlerEntry: StaticIoHandlerEntry { get }
}

/// A statically retained IO actor entry and numeric application context.
///
/// The macro-generated handler type supplies the concrete entry. The runtime
/// stores only that entry and the numeric context, so heterogeneous handlers
/// do not require a closure, existential, or heap box.
public struct StaticIoHandler<Handler: StaticIoActorHandler>: Sendable {
    /// Numeric application context passed to the handler.
    public let context: UInt32
    let entry: StaticIoHandlerEntry

    /// Creates a handler registration value.
    ///
    /// - Parameters:
    ///   - type: Macro-generated handler type.
    ///   - context: Numeric application context retained by the runtime.
    public init(_ type: Handler.Type = Handler.self, context: UInt32) {
        _ = type
        self.context = context
        self.entry = Handler.staticIoHandlerEntry
    }
}

/// Statically noncapturing handler ABI used by generated IO actor entries.
///
/// The arguments are numeric context, borrowed payload pointer and length,
/// representation, borrowed source and actor UUID bytes, receive time,
/// association generation, and route kind. Only the macro should normally
/// form values of this implementation-level type.
public typealias StaticIoHandlerFunction = @convention(c) (
    UInt32,
    UnsafePointer<UInt8>?, Int32,
    UInt8,
    UnsafePointer<UInt8>?, UnsafePointer<UInt8>?,
    UInt32, UInt32, UInt8
) -> Void

/// A concrete noncapturing handler entry generated for one application enum.
///
/// This public type is an implementation primitive required by macro
/// expansions in downstream modules. Prefer ``StaticIoActor(_:)`` over
/// constructing entries manually.
public struct StaticIoHandlerEntry: Sendable {
    /// C-convention callback. Its type makes captured state unrepresentable.
    public let function: StaticIoHandlerFunction

    /// Creates an implementation-level handler entry.
    ///
    /// - Parameter function: Statically noncapturing generated callback.
    public init(function: @escaping StaticIoHandlerFunction) {
        self.function = function
    }

    /// Decodes a payload for generated macro code.
    ///
    /// - Parameters:
    ///   - type: Concrete portable endpoint value type.
    ///   - payload: Borrowed payload pointer, or `nil` only for an empty value.
    ///   - payloadLength: Payload length bounded to the wire payload limit.
    ///   - representationRawValue: ``IoValueRepresentation`` raw value.
    /// - Returns: A decoded value, or `nil` for malformed inputs.
    public static func decode<Value: IoEndpointValue>(
        _ type: Value.Type,
        payload: UnsafePointer<UInt8>?,
        payloadLength: Int32,
        representationRawValue: UInt8
    ) -> Value? {
        guard payloadLength >= 0, payloadLength <= WireBufferConfig.maxPayloadSize,
              let representation = IoValueRepresentation(rawValue: representationRawValue),
              payload != nil || payloadLength == 0 else {
            return nil
        }
        if let fixedRepresentation = Value.fixedRepresentation,
           fixedRepresentation != representation {
            return nil
        }
        let pointer = payload ?? UnsafePointer<UInt8>(bitPattern: 1)!
        return try? Value.decodeIoPayload(
            ByteSlice(bytes: pointer, length: Int(payloadLength)),
            representation: representation
        )
    }

    /// Constructs delivery context for generated macro code.
    ///
    /// - Parameters:
    ///   - sourceID: Borrowed pointer to 16 source UUID bytes.
    ///   - actorID: Borrowed pointer to 16 actor UUID bytes.
    ///   - receivedAtMS: Caller-supplied monotonic receive time.
    ///   - associationGeneration: Processor association generation.
    ///   - routeKindRawValue: ``IoRouteKind`` raw value.
    /// - Returns: Complete delivery context, or `nil` for malformed inputs.
    public static func deliveryContext(
        sourceID: UnsafePointer<UInt8>?,
        actorID: UnsafePointer<UInt8>?,
        receivedAtMS: UInt32,
        associationGeneration: UInt32,
        routeKindRawValue: UInt8
    ) -> IoDeliveryContext? {
        guard let sourceID, let actorID,
              let routeKind = IoRouteKind(rawValue: routeKindRawValue) else {
            return nil
        }
        return IoDeliveryContext(
            sourceUUID: uuid(copying: sourceID),
            actorUUID: uuid(copying: actorID),
            receivedAtMS: receivedAtMS,
            associationGeneration: associationGeneration,
            routeKind: routeKind
        )
    }

    /// Invokes the generated entry through typed runtime values.
    ///
    /// All borrowed pointers remain valid only for the synchronous callback.
    ///
    /// - Parameters:
    ///   - context: Caller-owned numeric context handle.
    ///   - payload: Complete borrowed IO payload.
    ///   - representation: Endpoint representation fixed at registration.
    ///   - sourceID: Source endpoint UUID.
    ///   - actorID: Actor endpoint UUID.
    ///   - receivedAtMS: Caller-supplied monotonic receive time.
    ///   - associationGeneration: Processor association generation.
    ///   - routeKind: Public route classification.
    public borrowing func invoke(
        context: UInt32,
        payload: borrowing ByteSlice,
        representation: IoValueRepresentation,
        sourceID: UUID16,
        actorID: UUID16,
        receivedAtMS: UInt32,
        associationGeneration: UInt32,
        routeKind: IoRouteKind
    ) {
        let callback = function
        let localPayload = copy payload
        let sourceBytes = sourceID.bytes
        let actorBytes = actorID.bytes
        withUnsafeBytes(of: sourceBytes) { sourceBuffer in
            withUnsafeBytes(of: actorBytes) { actorBuffer in
                localPayload.withBytes { payloadPointer, payloadLength in
                    guard payloadLength <= WireBufferConfig.maxPayloadSize else { return }
                    callback(
                        context,
                        payloadPointer.assumingMemoryBound(to: UInt8.self),
                        Int32(payloadLength),
                        representation.rawValue,
                        sourceBuffer.baseAddress!.assumingMemoryBound(to: UInt8.self),
                        actorBuffer.baseAddress!.assumingMemoryBound(to: UInt8.self),
                        receivedAtMS,
                        associationGeneration,
                        routeKind.rawValue
                    )
                }
            }
        }
    }

    private static func uuid(copying bytes: UnsafePointer<UInt8>) -> UUID16 {
        UUID16(bytes: (
            bytes[0], bytes[1], bytes[2], bytes[3],
            bytes[4], bytes[5], bytes[6], bytes[7],
            bytes[8], bytes[9], bytes[10], bytes[11],
            bytes[12], bytes[13], bytes[14], bytes[15]
        ))
    }
}
