#!/bin/sh
# Copyright (c) 2026 Atakan DULKER. Licensed under the MIT License.

set -eu

scratch_path=${BUILD_DIR:-/workspace/.build}
cache_path=${SPM_CACHE_DIR:-/workspace/.swiftpm-cache}

exec swift run \
    --scratch-path "$scratch_path" \
    --cache-path "$cache_path" \
    --disable-automatic-resolution \
    axoloty-mcp "$@"
